# github-action-docker-buildx-build.yml
name: Run docker buildx build
description: Prepare the environment and run docker buildx build.
author: support@senzing.com

inputs:
   build-options:
      description: Additional options to pass to docker buildx build
   context:
      default: "."
      description: Context (directory) of the docker build process
   image-repository:
      description: Docker repository (e.g. senzing/senzingapi-runtime)
      required: true
   image-tag:
      default: latest
      description: Docker image tag
   password:
      description: Password for Docker registry
      required: true
   platforms:
      default: linux/amd64
      description: Comma-separated list of docker platforms to build (hint - See output of docker buildx ls)
   registry-server:
      default: docker.io
      description: Docker registry server
   username:
      description: Username for Docker registry
      required: true

runs:
   using: composite
   steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
           fetch-depth: "0"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker list platforms
        run: docker buildx ls
        shell: bash
      - name: Dockerhub login
        run: echo ${{ inputs.password }} | docker login -u ${{ inputs.username }} --password-stdin ${{ inputs.registry-server }}
        shell: bash
      - name: Docker build images
        run: |
           docker buildx build \
              --platform ${{ inputs.platforms }} \
              --tag ${{ inputs.registry-server }}/${{ inputs.image-repository }}:${{ inputs.image-tag }} \
              --tag ${{ inputs.registry-server }}/${{ inputs.image-repository }}:latest \
              ${{ inputs.build-options }} \
              ${{ inputs.context }}
        shell: bash

branding:
   icon: upload-cloud
   color: green
