name: make-latest-tag.yaml

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

jobs:
  make-go-tag:
    name: Make a latest tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: "0"
      - name: Run latest-tag
        uses: EndBug/latest-tag@latest
